# USE AN OFFICAL IMAGE OF NODE
FROM node:alpine 
# SET THE WORKING DIRECTORY
WORKDIR /app
# COPY THE PACKAGE.JSON AND PACKAGE-LOCK.JSON FILES
COPY package*.json ./
# INSTALL THE DEPENDENCIES
RUN npm install --only=production
# COPY THE REST OF THE APPLICATION CODE
COPY . .
# EXPOSE THE PORT
EXPOSE 3000
# START THE APPLICATION
CMD ["npm", "start"]