name: CI/CD Pipeline Using Github Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Nodejs # setting up Node.js environment 
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: SonarQube Cloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.1
        with:
            args: >
              -Dsonar.projectKey=AbhishekCS3459_CI-CD_AWS_Learnings
              -Dsonar.organization=abhishekcs3459
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: ✅ Build Successful
        run: echo "🎉 Build and analysis completed successfully!"
      - name: Build Docker Image 
        run: docker build -t $GITHUB_SHA .
       
      - name: Trivy Scan 
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image $GITHUB_SHA 